//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Book
    {
        public int BookID { get; set; }
        [Required(ErrorMessage ="Xin vui lòng nhập sách"), MaxLength(100,
            ErrorMessage ="Tên sách không dài hơn 100 ký tự"),DisplayName("Tên sách")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Xin vui lòng chọn tác giả"), DisplayName("Tác giả")]
        public int AuthorID { get; set; }
        [DisplayName("Đơn giá")] 
        public Nullable<decimal> Price { get; set; }
        [DisplayName("Hình ảnh")]

        public string Images { get; set; }
        [Required(ErrorMessage = "Xin vui lòng chọn chủ đề sách"), DisplayName("Chủ đề sách")]
        public int CategoryID { get; set; }
        [DisplayName("Mô tả")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Ngày xuất bản"), DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}",ApplyFormatInEditMode =true)]
        public Nullable<System.DateTime> Published { get; set; }
        [DisplayName("Số lần xem")]
        public Nullable<int> ViewCount { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}
